# Solving TSP with Dynamic Programming

### Import the required libraries

In [106]:
import sys
import copy
import numpy as np 
import pandas as pd
from matplotlib import pyplot as plt

In [107]:
top_dests_ktm=pd.read_csv("../destinations_of_kathmandu_updated_with_latlong.csv")
print(top_dests_ktm.head())

                  title avg_rating  voted_by            genre    latitude  \
0      Boudhanath Stupa        4.5      8897  Religious Sites  27.7215062   
1  Swayambhunath Temple        4.5      6203  Religious Sites  27.7149298   
2  Pashupatinath Temple        4.5      4937  Religious Sites  27.7104461   
3     Chandragiri Hills        4.5       399        Mountains  27.6710496   
4       Kopan Monastery        4.5       787  Religious Sites  27.7425438   

   longitude  
0  85.359809  
1  85.288146  
2  85.346503  
3  85.262664  
4  85.362208  


In [108]:
# select the first 95 destinations as they're the destinations having the latitude and longitude currently
top_dests_ktm=top_dests_ktm[:95]
print(top_dests_ktm.tail())

                         title avg_rating  voted_by  \
90     Ghanta Ghar Clock Tower        3.5        11   
91  Jamchen Lhakhang Monastery        3.5         3   
92                    Big Bell        3.5         9   
93       Mrigasthali Deer Park          4         5   
94            Universal Crafts          5         3   

                              genre    latitude  longitude  
90   Points of Interest & Landmarks   27.707477  85.314711  
91                  Religious Sites  27.7215058  85.359192  
92   Points of Interest & Landmarks  27.7268583  85.300625  
93  Nature & Wildlife Areas • Parks   27.711512  85.349772  
94    Art Galleries • Antique Shops  27.7173331  85.381252  


In [109]:
# let's just pick n=10 for now for better visualization
n=95 #graph size
top_n_dests=top_dests_ktm[:n]
print(top_n_dests)

                         title avg_rating  voted_by  \
0             Boudhanath Stupa        4.5      8897   
1         Swayambhunath Temple        4.5      6203   
2         Pashupatinath Temple        4.5      4937   
3            Chandragiri Hills        4.5       399   
4              Kopan Monastery        4.5       787   
..                         ...        ...       ...   
90     Ghanta Ghar Clock Tower        3.5        11   
91  Jamchen Lhakhang Monastery        3.5         3   
92                    Big Bell        3.5         9   
93       Mrigasthali Deer Park          4         5   
94            Universal Crafts          5         3   

                              genre    latitude  longitude  
0                   Religious Sites  27.7215062  85.359809  
1                   Religious Sites  27.7149298  85.288146  
2                   Religious Sites  27.7104461  85.346503  
3                         Mountains  27.6710496  85.262664  
4                   Religious Site

In [110]:
# since we'll be dealing only with latitude and longitude at the moment
# only filter those columns along with the title
print(top_dests_ktm[['title','latitude','longitude']])

                         title    latitude  longitude
0             Boudhanath Stupa  27.7215062  85.359809
1         Swayambhunath Temple  27.7149298  85.288146
2         Pashupatinath Temple  27.7104461  85.346503
3            Chandragiri Hills  27.6710496  85.262664
4              Kopan Monastery  27.7425438  85.362208
..                         ...         ...        ...
90     Ghanta Ghar Clock Tower   27.707477  85.314711
91  Jamchen Lhakhang Monastery  27.7215058  85.359192
92                    Big Bell  27.7268583  85.300625
93       Mrigasthali Deer Park   27.711512  85.349772
94            Universal Crafts  27.7173331  85.381252

[95 rows x 3 columns]


In [111]:
# also meanwhile let's create a matrix called 'graph' to store the weights for each edges
graph=np.zeros((n,n))

def create_graph():

    # iterators to iterate through the graph
    i=0
    j=0

    for lat,long in zip(top_n_dests['latitude'].astype(float),top_n_dests['longitude'].astype(float)):
        j=0
        for another_lat,another_long in zip(top_n_dests['latitude'].astype(float),top_n_dests['longitude'].astype(float)):
            #edge weight(Euclidean distance)
            distance_between_the_places=np.sqrt((lat-another_lat)**2+(long-another_long)**2)
            #print(distance_between_the_places)

            #and store it in the 'graph' matrix
            graph[i][j]=distance_between_the_places
            #increment j 
            j+=1

        #increment i
        i+=1

In [112]:
create_graph()
print(graph)

[[0.         0.07196422 0.01730239 ... 0.05942541 0.01416395 0.0218452 ]
 [0.07196422 0.         0.05852919 ... 0.01726324 0.0617212  0.09313701]
 [0.01730239 0.05852919 0.         ... 0.04872526 0.00343867 0.03542471]
 ...
 [0.05942541 0.01726324 0.04872526 ... 0.         0.05148753 0.0811875 ]
 [0.01416395 0.0617212  0.00343867 ... 0.05148753 0.         0.03201319]
 [0.0218452  0.09313701 0.03542471 ... 0.0811875  0.03201319 0.        ]]


In [113]:
# input matrix containing cost
matrix = graph
# input data points
data = list(range(0,n))

In [114]:
# initializing necessary parameters
all_sets = []
g = {}
p = []
starting_node=1

In [115]:
def main():
    """
        Main function
    """
    
    route=[] #to store the final route
    
    for x in range(1, n):
        g[x + 1, ()] = matrix[x][0]
    
    # minimum cost
    min_cost=get_minimum(starting_node, tuple(range(2,10)))
    print("Miniumum cost: ",min_cost)
    print('\n\nSolution to TSP: {1, ', end='')
    
    route.append(1) #append the starting node
    
    solution = p.pop()
    print(solution[1][0], end=', ')
    route.append(solution[1][0])
    for x in range(n - 2):
        for new_solution in p:
            if tuple(solution[1]) == new_solution[0]:
                solution = new_solution
                print(solution[1][0], end=', ')
                route.append(solution[1][0])
                break
    print('1}')
    route.append(1)#append the ending node (same as starting node)
#     print(route)
    return route

In [116]:
def get_minimum(k, a):
    """
        Get the minimum cost
    """
    if (k, a) in g:
        # Already calculated Set g[%d, (%s)]=%d' % (k, str(a), g[k, a]))
        return g[k, a]

    values = []
    all_min = []
    for j in a:
        set_a = copy.deepcopy(list(a))
        set_a.remove(j)
        all_min.append([j, tuple(set_a)])
        result = get_minimum(j, tuple(set_a))
        values.append(matrix[k-1][j-1] + result)

    # get minimun value from set as optimal solution for
    g[k, a] = min(values)
    p.append(((k, a), all_min[values.index(g[k, a])]))

    return g[k, a]


In [117]:
if __name__ == '__main__':
    route=main()

Miniumum cost:  0.7661192774309632


Solution to TSP: {1, 3, 7, 6, 9, 2, 4, 8, 5, 1}


In [118]:
#cross-checking the total cost
total_cost=0 #initialize total cost to 0
for i in range(0,len(route)-1):
    total_cost=total_cost+matrix[route[i]-1][route[i+1]-1]
print(total_cost)

0.7661192774309633


In [119]:
for i in route:
    print(top_n_dests.iloc[i-1]["title"],end='')
    print("--->",end='')

Boudhanath Stupa--->Pashupatinath Temple--->Garden of Dreams--->Thamel--->Kathmandu Durbar Square--->Swayambhunath Temple--->Chandragiri Hills--->Namo Buddha (Stupa)--->Kopan Monastery--->Boudhanath Stupa--->